In [1]:
from sklearn.datasets import fetch_openml 
import numpy as np
mnist = fetch_openml('mnist_784', version=1)

In [32]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [33]:
X,y = mnist.data,mnist.target

In [34]:
y = y.sort_values()

In [35]:
y.index

Int64Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388,
            56429,
            ...
            13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678,
            58529],
           dtype='int64', length=70000)

In [36]:
X = X.reindex(y.index)

In [37]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [38]:
y_train.describe()

count     56000
unique        8
top           1
freq       7877
Name: class, dtype: object

In [39]:
y_test.describe()

count     14000
unique        3
top           9
freq       6958
Name: class, dtype: object

In [40]:
# nie da sie osiagnac takiego podzialu. funkcja train_test_split, bo dokonuje ona pomieszania przed podzieleniem

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

In [42]:
y_train.describe()

count     56000
unique       10
top           1
freq       6285
Name: class, dtype: object

In [43]:
y_test.describe()

count     14000
unique       10
top           1
freq       1592
Name: class, dtype: object

In [44]:
y0_train = (y_train == '0')
y0_test = (y_test == '0')

In [45]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
clf = SGDClassifier()

In [46]:
clf.fit(X_train,y0_train)
y0_pred_train = clf.predict(X_train)
y0_pred_test = clf.predict(X_test)
acc_train = accuracy_score(y0_train,y0_pred_train)
acc_test = accuracy_score(y0_test,y0_pred_test)

In [47]:
acc_train

0.9841964285714285

In [48]:
acc_test

0.9820714285714286

In [49]:
y0_train

32576    False
10306    False
37102    False
57835    False
15160     True
         ...  
57853    False
3896      True
68497    False
20351     True
36463    False
Name: class, Length: 56000, dtype: bool

In [50]:
from sklearn.model_selection import cross_val_score
cva = cross_val_score(clf, X_train, y0_train, cv=3)
acc = [acc_train, acc_test]

In [51]:
import pickle
with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump(acc,f)
with open('sgd_cva.pkl', 'wb') as f:
    pickle.dump(cva,f)

In [ ]:
clf2 = SGDClassifier(max_iter=1000)
clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)
conf_mat = confusion_matrix(y_test, y_pred)

In [ ]:
print(conf_mat)

In [ ]:
with open('sgd_cmx.pkl','wb') as f:
    pickle.dump(conf_mat, f)

In [ ]:
cva

In [ ]:
acc