In [3]:
from sklearn.datasets import fetch_openml 
import numpy as np
mnist = fetch_openml('mnist_784', version=1)

In [4]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [15]:
X,y = mnist.data,mnist.target

In [16]:
y = y.sort_values()

In [17]:
y.index

Int64Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388,
            56429,
            ...
            13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678,
            58529],
           dtype='int64', length=70000)

In [18]:
X.reindex(y.index)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [19]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [22]:
y_train.describe()

count     56000
unique        8
top           1
freq       7877
Name: class, dtype: object

In [23]:
y_test.describe()

count     14000
unique        3
top           9
freq       6958
Name: class, dtype: object

In [24]:
# nie da sie osiagnac takiego podzialu. funkcja train_test_split, bo dokonuje ona pomieszania przed podzieleniem

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
y_train.describe()

count     56000
unique       10
top           1
freq       6285
Name: class, dtype: object

In [28]:
y_test.describe()

count     14000
unique       10
top           1
freq       1592
Name: class, dtype: object

In [47]:
y0_train = (y_train == '0')
y0_test = (y_test == '0')

In [48]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
clf = SGDClassifier(max_iter=1000)

In [49]:
clf.fit(X_train,y0_train)
y0_pred_train = clf.predict(X_train)
y0_pred_test = clf.predict(X_test)
acc_train = accuracy_score(y0_train,y0_pred_train)
acc_test = accuracy_score(y0_test,y0_pred_test)

In [50]:
acc_train

0.90075

In [51]:
acc_test

0.902

In [ ]:
from sklearn.model_selection import cross_val_score
cva = cross_val_score(clf, X_train, y_train, cv=3)
acc = [acc_train, acc_test]

In [ ]:
import pickle
with open('sgd_acc.pkl', 'w') as f:
    pickle.dump(acc,f)
with open('sgd_cva.pkl', 'w') as f:
    pickle.dump(cva,f)

In [52]:
clf2 = SGDClassifier(max_iter=1000)
clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)
conf_mat = confusion_matrix(y_test, y_pred)

In [53]:
print(conf_mat)

[[  7 100 492  19   9   2  65  50 588  33]
 [ 10 163 564  21  16   2  82  52 650  32]
 [  5 110 460  10   4   0  75  50 647  28]
 [  6 108 440  24  10   1  56  41 681  27]
 [  6 107 474  14   9   1  79  43 603  30]
 [  6 111 437  13  10   0  54  45 605  29]
 [  6 104 474  19   7   3  56  53 638  39]
 [  3 101 488  22   8   1  63  46 673  38]
 [ 12 112 471  22  14   0  68  37 596  38]
 [  6  97 507  16  10   0  62  35 607  32]]


In [ ]:
with open('sgd_cmx.pkl','w') as f:
    pickle.dump(conf_mat, f)